### ISSUE TITLE
New Version Export as CSV give HTML Format

### ISSUE THREAD

**Issue by gwena56** [thunderbird/import-export-tools-ng#451]
Hello, many tanks for this excellent Thunderbird Plug-in ... there is a way to have text export for body message in CSV ? i use it from the previous version .. Best regards

**Comment by cleidigh** [comment]
@gwena56 
I believe I have observed this in v14.
I will address the shortly in the first beta.
Thanks for finding this!
@cleidigh

**Comment by cleidigh** [comment]
@gwena56 

I have the first v14.0.1 beta with the correct text output for CSV exports.
You can grab it from the release status 
- #466 
@cleidigh

**Comment by cleidigh** [comment]
@gwena56 
Did you get a chance to try the beta?
@cleidigh

**Comment by cleidigh** [comment]
@gwena56 
Great, glad you are back up and running! And I love hearing about the creative ways people use IETNG like yourself.

Appreciate the support and patience, this release was tough, but I should have caught this, never enough time!
Cheers 
Christopher
