### ISSUE TITLE
The option to import pst files is no longer available

### ISSUE THREAD

**Issue by pipounix** [thunderbird/import-export-tools-ng#490]
The option to import pst files is no longer available

**Comment by cleidigh** [comment]
@pipounix 
I am not sure exactly what you are referring to, IETNG never had the feature of handling either import or export of pst files?
@cleidigh

**Comment by pipounix** [comment]
Following chatgpt's recommendation, it tells me to use importexporttool-ng to import it as chatgpt only has information until 2021. I assumed that this option is in a previous version and not in the new version. Since I couldn't find a place to give recommendations, I chose to mark it as An issue other than being a failure, if they added that function it would be very useful for more people to migrate from Outlook to Thunderbird, thank you very much!!!

**Comment by cleidigh** [comment]
@pipounix 
You are absolutely correct this would be helpful for migrating Outlook users. At a minimum I should probably gather information on the various tools that convert PST to eml or mbox that IETNG will import.

To be honest with everything I have to do I am worried about dealing with the Microsoft oddities. How would you feel about the converters out there?
@cleidigh

**Comment by pipounix** [comment]
The problem with the converters that exist is not that they are bad, the question is always the money, those that are good are paid and even so I have to resort to a third-party application when the ideal would be for the same application to have the necessary import options already. In case migrating people to free software is difficult because they are people of habit, not having the options to make it easy complicates it!! And thank you for responding. If I find information that I think is important about export/import, I can share it with you through this medium. I like to help with projects!!
