### ISSUE TITLE
No options shown to import data 

### ISSUE THREAD

**Issue by sam-pudle** [thunderbird/import-export-tools-ng#492]
W11, Thunderbird 115.4.1 (64 bit)
---

Ive exported a copy of an IMAP email account using the tool. 

I want to re-import the data to check it. 

Ive watched a video on line [here](https://www.youtube.com/watch?v=2VjpbYvs_QA) - which shows you can go to local folders and then import, see screenshot here - https://imgur.com/a/PFg84l3 (this screenshot is from the above video)

But when i try this myself i dont get an import options, see screenshot here - https://imgur.com/a/gXclPqb

Any ideas why i dont get the import options ?

Am i trying to import this data the right way ?

**Comment by cleidigh** [comment]
@sam-pudle 
I am assuming you are running the current release v14.0.0. With the complete menu redesign I had some differences from pre 115 versions including not having account level import, you have to create a Local Folders subfolder and right click on that for import.
I have, however, re-implemented account level import in beta for v14.0.1.
You can grab here:
https://github.com/thunderbird/import-export-tools-ng/issues/466
@cleidigh

**Comment by cleidigh** [comment]
@sam-pudle 
Were you able to try the beta?
@cleidigh

**Comment by sam-pudle** [comment]
@cleidigh thanks for the message, I tried to download but the link wouldnt work - https://github.com/thundernest/import-export-tools-ng/blob/v14.0.1/xpi/beta/import-export-tools-ng-14.0.1-b8-tb.xpi

**Comment by cleidigh** [comment]
@sam-pudle 
Not sure why the link doesn't work, however, the v14.0.1 was released today so you can download from the addon site.
@cleidigh
