### ISSUE TITLE
[Feature Request]: Support for Exporting a mail via Drag + Drop

### ISSUE THREAD

**Issue by FrankHuxol** [thunderbird/import-export-tools-ng#502]
I would really love to see a drag + drop support. My use case:
I need to archive a few of my mails (not all of them, just important ones) on a shared and backed up drive. I do have to follow a specific file name pattern, including for instance the date + time of that mail.

I am currently using import-export-tools for that, but the workflow could be better:
* Right click the mail
* Navigate to the correct export format (which is always the same for me), a folder choose opens up.
* Go to the explorer, where I usually already have my target directory on the network drive open. Copy the location
* Got back to the folder chooser, paste and hit OK twice

It would be really helpful, if I could just drag + drop the mail to my destination explorer window (which actually already exports the file, but with default thunderbird settings) and then the exported file would use the file name format as specified in the import-export-tools.

**Comment by cleidigh** [comment]
@FrankHuxol 
Thanks for the post.
This is something I have not contemplated nor received any similar request. Given the complexity of adding something like this and my endless todo list, I have to be honest I don't see something like this happening.

That said, there are a couple of things you can already do to streamline your work flow.
First you can setup to use a default export directory eliminating the folder picking all together.
Second you can use TBKeys addon to define a key to trigger the type of export.

@cleidigh

**Comment by FrankHuxol** [comment]
Thank you very much for your response. Also thanks for that really nice addon.

Sadly, I can't really use of the default export directory, because the mails I need to export usually go into very different directories. However, I gave the TBKeys addon a try and mapped the "e"-key to do an export.

For reference for others: This is my configuration in tbkeys-lite:
{
    "e": "func:exportSelectedMsgs"
}

With this approach, I am quite happy, so thanks again for that input.

**Comment by cleidigh** [comment]
@FrankHuxol 
Great. Well  I am pleased this approach improves things!
Thanks for the support.
Reviews always appreciated %-)
@cleidigh

**Comment by FrankHuxol** [comment]
If you have a rough idea on how drag + drop could be implemented, you can point me in that direction. I've provided a merge request to one other TB addon already, but there I got a good guideline on what excactly to do. I guess, "implementing drag + drop" is not as straightforward, but if time permits, I could give it a go.

**Comment by cleidigh** [comment]
@FrankHuxol 
I will be honest I have done nothing with DnD in Thunderbird.
There are several difficult aspects I could forsee. Working with a split web extension and legacy code, doing export on the drop side and what Thunderbird is capable in doing with the external explorer side to name a few.
@cleidigh

**Comment by FrankHuxol** [comment]
Alright, given the current workaround fits 90% of my workflow, I think I am not motivated enough to work my way through this. Closing this issue as "Won't fix".
