### ISSUE TITLE
Customize Charset and Filename Length for Attachments

### ISSUE THREAD

**Issue by karQs** [thunderbird/import-export-tools-ng#514]
I'm trying to export HTML files with attachments to a server that only supports file lengths up to 143 characters and no special characters. I'm able to use the options in the GUI to have the HTML files meet this requirement but the attachments retain their original name. Is there a way to limit the attachment files to a specific length and charset?

**Comment by cleidigh** [comment]
@karQs 
Thanks for the post.
Yes my swiss knife file naming options don't really extend down to the attachments themselves. So let's break down your requirements.
First the max path length (would love to know what vintage server restricts to 143 chars %-})

So unlike the message names, we really can only affect the length by changing the Attachment folder name format. So we can change from the default "Attachments" (11 chars) to just "a", Then of course you will have indexed suffixes "a-1" etc.
The length of the actual attachment name is as is. I'm not sure what I would do there other than a true cut of the name excepting the extension. Then you have to be wary of similar names from one message.

So the container is foldername + 8 chars 
Then messages + a(+3 for up to 100 att folders) + attachment name

So if you had one character folder names your minimum overhead is 21 chars. That leaves you with 122 chars for an attachment name. Are you hitting that limit?

Second, characters in attachment names. This is arguably a bug on my part as I don't escape the attachment filenames. This is something I could change in a beta.

So I'm hoping that the filename length is manageable and with the addition of escaping you would be good.
@cleidigh

**Comment by cleidigh** [comment]
@karQs 
Any comments?
@cleidigh

**Comment by karQs** [comment]
Unfortunately the limit is on the actual file name, not the full path, and I have some attachments with long names. My solution was to just skip copying the attachments folder and if I need an attachment I can access the .eml for that message.

As to the filesystem, it's a Synology Nas, in which encrypted folders are limited to 143 characters for filenames.

**Comment by cleidigh** [comment]
@karQs 
Ok so I can close?
@cleidigh
