### ISSUE TITLE
disappeared remote folder export function in Import export tool NG v. 14.01

### ISSUE THREAD

**Issue by stecolumna** [thunderbird/import-export-tools-ng#520]
with the upgrade to the latest version of thunderbird 115.6.0 (64 bit) for Linux the export remote folder function (for IMAP account) in the Import export tool NG extension v. 14.01 disappeared for me and therefore I can't back up my year 2023 email
stecolumna

**Comment by cleidigh** [comment]
@stecolumna 
The new mbox export uses the same export method for local and remote folders. You can therefore export with the standard export mbox menu options.
@cleidigh

**Comment by stecolumna** [comment]
Dear @cleidigh 
thank you for the answer
Best regards,
@stecolumna
