### ISSUE TITLE
Viewing eml with Quick Look in Sonoma

### ISSUE THREAD

**Issue by memphis-10** [thunderbird/import-export-tools-ng#522]
Hi,

Excellent plugin!

I recently upgraded from Mojave to Sonoma.  Now, when using Quick Look (spacebar preview) to check an eml file, only the header info is visible.  I use this combo all the time to find what I need where I save eml with the plugin, and check the eml with Quick Look before opening, or re-importing.  

Is there a way to get it back where the entire message is viewable in Quick Look?

Previewing the same message saved with Apple Mail shows the body contents.

Importexport tools saved eml
![Screenshot 2024-01-15 at 5 02 16 PM](https://github.com/thunderbird/import-export-tools-ng/assets/88346417/12ebed05-ba76-4235-b38e-acb7d058c404)

Apple mail saved eml (drag and drop message to desktop)
![Screenshot 2024-01-15 at 5 02 23 PM](https://github.com/thunderbird/import-export-tools-ng/assets/88346417/d00b3686-9bee-4a5f-990c-d3bcea94b9ed)

**Comment by memphis-10** [comment]
I found this, which indicated that all my old saves would no longer work, which has now been confirmed.  Maybe helpful to implement in the future?

https://www.karma.net/2020/10/26/quicklook-eml-catalina

**Comment by cleidigh** [comment]
@memphis-10 
Thanks for the post and compliment!
So I'm not an osx expert and my mac won't run Sonoma.
I did a search and found that Apple appears to have broken quicklook support for eml files.
One example : 
https://discussions.apple.com/thread/253930941?sortBy=best

The fact that files saved with apple mail works is odd, but I suspect it's some osx mapping. I don't see what I can do. I can't change the eml format.
@cleidigh

**Comment by memphis-10** [comment]
Cheers, thank you for getting back.  I used OCLP to get into Sonoma, but that's another post.  

I created the script mentioned above and tested on individual files and it works to preview the eml again.  It has something to do with carriage returns.  I'll have to see if I can figure out how to process my full archive.

**Comment by cleidigh** [comment]
@memphis-10 
Our posts crossed.
Yes I saw the line ending issue after.
For new exports you can use the strip CR option.
@cleidigh

**Comment by memphis-10** [comment]
Ah, cheers, I did not see that!  Thank you very much, that solves the issue for new saves.  I hope this helps more people along the way!
