### ISSUE TITLE
How to import mbox with different "Date:" formats?

### ISSUE THREAD

**Issue by FrankieTheFluff** [thunderbird/import-export-tools-ng#524]
How can I import a MBOX with different "Date:" formats within the emails?

E.G.:

Works:
Date: Sun, 05 Aug 2007 09:11:09 -0700

Doesn't work:
Date: 1999/01/31

Greetings Frank

**Comment by cleidigh** [comment]
Hmmm, that's a totally non standard format.
Can you tell me the origin of these dates?
I can see about an exception rule, already have some.
Christopher

**Comment by FrankieTheFluff** [comment]
I found on archive.org some mbox files from old FIDOnet / Usent echos.
e.g. https://archive.org/download/usenet-fido.ger
They included mixed "Date:" field formatings

**Comment by FrankieTheFluff** [comment]
sorry, wrongt URL - I edited

**Comment by cleidigh** [comment]
Any chance you could send one message?

**Comment by FrankieTheFluff** [comment]
Sure
[fido.belg.beer.mbox.zip](https://github.com/thunderbird/import-export-tools-ng/files/14076508/fido.belg.beer.mbox.zip)

**Comment by cleidigh** [comment]
thanks,
can't promise, but I will see

**Comment by cleidigh** [comment]
@FrankieTheFluff 
What is the largest size mbox you have.
This is tricky based on current import method.
@cleidigh

**Comment by FrankieTheFluff** [comment]
Well, size could be 100MB.

I also thought about programming by myself a small "date converter".
Like loading the mbox file as a stream and go through every line beginning with "Date: " and save it then.
But I didn't try how possible big stream could be...

**Comment by cleidigh** [comment]
@FrankieTheFluff 
So the minimal date format Thunderbird will accept is
mm-dd-yyyy
I think I will do this as a test version with a regex. It will be limited to 200MB.I won't put this into production.
@cleidigh

**Comment by cleidigh** [comment]
@FrankieTheFluff 
Ok give this a whirl...
https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.2-b9-t1/xpi/beta/import-export-tools-ng-14.0.2-b1-tb.xpi

It did fine on your mbox you posted. Note - reboot after installing.
Now you have me hankering for a Belgian wheat %-)
Christopher

**Comment by FrankieTheFluff** [comment]
Hi,
thank you for this - I will try later 
Greetz

**Comment by FrankieTheFluff** [comment]
Hi Christopher,
I tested it and worked just great.
Thank you very much

Oh yes, some belgian stuff ;)

**Comment by cleidigh** [comment]
@FrankieTheFluff 
Excellent.
Glad to be of service.
I would gladly accept a review versus a virtual beer %-)
Christopher
