### ISSUE TITLE
Extended file name format not working

### ISSUE THREAD

**Issue by JensHauser** [thunderbird/import-export-tools-ng#527]
I´d like to export mails as EML into a folder with a specific file format
`${subject}-!x!-${sender_email}-!x!-${recipient_email}-!x!-${date}`

This is the configuration page
![grafik](https://github.com/thunderbird/import-export-tools-ng/assets/44340656/4a212ed2-7054-4c95-aa35-ddf6fd14f8fd)

![grafik](https://github.com/thunderbird/import-export-tools-ng/assets/44340656/9dc2b1de-5799-4d21-925c-3cf0d65fb0ef)

The output
`test - Jens Hauser (myEmailAdress@something.de) - 2024-01-17 1705.eml`

I expected
`test-!x!-Jens Hauser (myEmailAdress@something.de)-!x!-Jon Doe (hisEmailAdress@something.de)-!x!-2024-01-17 1705.eml`

Did I miss a checkbox?

**Comment by cleidigh** [comment]
@JensHauser 
That's odd as your output looks like the simple type, but not matching any actual settings.
I tried your settings with success although the date format is different because the ${date} is different than your expectations.
print again-!x!-t1@gmail.com-!x!-Test1@kokkini.net-!x!-20231227.eml
Is my output.

I have seen some inexplicable options oddities that I have not been able to explain.

Let's try the following : 
- Go to options 
- choose Use this format
- Uncheck Extended format (ui bug)
- Click ok
- Try export, note result
- Back to options 
- Click extended format, ok
- Try export again 

Note I did test under de locale, worked as well 
@cleidigh

**Comment by JensHauser** [comment]
(case 1)
![grafik](https://github.com/thunderbird/import-export-tools-ng/assets/44340656/2e72439d-f16f-4f71-9a97-ea3165c348b9)
leads to
`Re  [thunderbird_import-export-tools-ng] Extended file name format not working (Issue #527) - Christopher Leidigh (notifications@github.com) - 2024-01-29 1943.eml`

and

(case 2)
![grafik](https://github.com/thunderbird/import-export-tools-ng/assets/44340656/a863b5b0-8ad3-40f9-badc-60e079d2b6ac)
leads to
`Re  [thunderbird_import-export-tools-ng] Extended file name format not working (Issue #527) - Christopher Leidigh (notifications@github.com) - 2024-01-29 1943.eml`

Looks like the extended settings are ignored.
While playing with the 2 check boxes, I realized the following (but happened 2 of 5 times)

- checked "Use this format" only
- "ok"
- .... saved ...
- back to the dialog
- still "Use this format" checked
- clicked on "extended format"
- BOTH were checked now

(case 3)
![grafik](https://github.com/thunderbird/import-export-tools-ng/assets/44340656/ead0ae58-7244-475d-abe8-573868d4177c)
`Re  [thunderbird_import-export-tools-ng] Extended file name format not working (Issue #527) - Christopher Leidigh (notifications@github.com) - 2024-01-29 1943.eml`

Other times, the "use this format" checkbox was unchecked and "extended format" checked automatically (same result)

In all cased the output is identical, see above.

Looks like the settings are all ignored?

---

I learned something:
* I saved the mail via CTRL-S (seems the add-on doesn´t apply). Trapdoor I stepped into.
* Saving via right click on the message / export as embedded EML leads to
* `Re_[thunderbird_import-export-tools-ng] Extended f-_x_-notifications@github.com-_x_-import-export-tools-ng@noreply.github.com-_x_-20240129.eml`

The pipe symbol was replaced by an underscore.

Summary
* Subject with saving via CTRL-S solved.
 could the add-on be applied for CTRL-S, if activated?
* checkboxes potential issue (usability)
* issue - pipe replaced by underscore

**Comment by cleidigh** [comment]
@JensHauser 
Thanks for the report.
Control-S is Thunderbird save so nothing to do with IETNG.
You can use tbkeys, not tbKeys-lite to create a shortcut.
Yes, need ui patch.
The pipe is not a valid os filename character, always replaced with underscores.
@cleidigh

**Comment by JensHauser** [comment]
Thanks a lot, subject is solved for me by taking another character playing the role of a divider.

Please allow a hint - it´s about naming filename conventions.
According to this [Microsoft document](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) a certain set of characters is not allowed.

I tried with an exclamation mark (IMHO: allowed), exported and it´s been replaced by an underscore.

So my vote is to allow the linked characters in the add-on.
