### ISSUE TITLE
Sorry, cannot find menu item to import .eml files

### ISSUE THREAD

**Issue by jbusch223** [thunderbird/import-export-tools-ng#530]
Hi import-export-tools-ng -

I've spent some time trying to find the answer anywhere but here, because I hate to pester developers.  I need to import messages saved as .eml files to folders in my Thunderbird profile.  I'm on version 115 in Windows Pro 10.  The files were saved as .eml using ImportExportToolsNG and are in folders in a temporary folder in root.  I only see an option to import MBOX.  Please see the screen shot.  I'm clear that importing .eml is a listed feature, so I must be missing something.  Please help.

Apologies again and many thanks in advance -
jbusch223

![ImportExportTools](https://github.com/thunderbird/import-export-tools-ng/assets/158457232/c191d062-3112-4065-bd17-7ec088014982)

**Comment by cleidigh** [comment]
@jbusch223 
No sorry necessary!
Since mboxes represent folders, these are allowed to be imported at the account level.
To import eml messages, create a folder under Local Folders then right click on that and you will see the eml import options.
@cleidigh

**Comment by jbusch223** [comment]
Many thanks Christopher!  I will give it a try.

**Comment by cleidigh** [comment]
Let me know if you are  good...
Christopher

**Comment by cleidigh** [comment]
@jbusch223 
Glad you are all set!
Ok to close?
Christopher

**Comment by jbusch223** [comment]
Sure.  I forgot to go back and do that myself, thanks!
