### ISSUE TITLE
Can't import mbox folder and subfolders (option not exist)

### ISSUE THREAD

**Issue by hiperiondev** [thunderbird/import-export-tools-ng#532]
OS: Windows 10 (64 bits)
Thunderbird: 115.7.0 (64 bits)
ImportExportTool NG: v14.0.1

I don't have import mbox with subfolders option!
Import all mbox files from directory not work with subfolders

**Comment by cleidigh** [comment]
@hiperiondev 
All the folder import and export options are found by right clicking on a folder.
@cleidigh

**Comment by hiperiondev** [comment]
I do exactly that and there is no import (in local folders) MBOX with subfolders. You can only import folder by folder where the MBOX files are located, not the entire structure.
In previous versions this option existed.
Without this, importing complete accounts from Outlook is very uncomfortable!

**Comment by cleidigh** [comment]
@hiperiondev 
Are you trying to import to a maildir, that is not possible?
@cleidigh

**Comment by hiperiondev** [comment]
I have an export folder with BitRecover PST Converter Wizard
This returns a folder with subfolders of each Outlook folder, and within these the MBOX files

**Comment by cleidigh** [comment]
@hiperiondev 
Buut is your account setup as a maildir storage? You can't import mboxes to a maildir account.
@cleidigh

**Comment by hiperiondev** [comment]
I have a pop account, and I want to import the old Outlook folders on a Local Folder for historical reasons

**Comment by cleidigh** [comment]
@hiperiondev 
Ok, but is the pop account setup for mbox or maildir storage? Look in your account manager for the main account and the local folders account.

@cleidigh

**Comment by cleidigh** [comment]
Also try creating a folder under Local Folders and right click on that to import there

**Comment by hiperiondev** [comment]
I have created a folder under Local Folders. But I only can import folder by folder. Selecting the top folder of the migrated files not import anything

**Comment by cleidigh** [comment]
@hiperiondev 
ok so I assume you are past the menu issues and you did find the import with structure option?
If so then it may be your export structure. Can you post what the file structure looks like?

**Comment by hiperiondev** [comment]
```
-- MIGRATED
---- MAIN FOLDER
-------- Account_1
------------ Inbox
---------------- Inbox.mbox 
------------ Sended
---------------- Sended.mbox
[...]
-------- Account_2
[...]
-------- Account_n
```

**Comment by cleidigh** [comment]
@hiperiondev 
Your pst converter does not look like it exports to the Thunderbird and other clients sbd structure with subfolders in a sbd folder.
That's what IETNG has always expected. Without that structure you will have to import folder by folder.
@cleidigh

**Comment by hiperiondev** [comment]
That's correct, it doesn't export sbd files, only MBOX files

**Comment by cleidigh** [comment]
It's not sbd files, it's folders. The expected structure is this
Account
 inbox.mbox
 inbox.sbd (folder)
   sub1.mbox
   sub2.mbox

etc

**Comment by hiperiondev** [comment]
Thanks so much for the explanation. I will look for other export software.

**Comment by cleidigh** [comment]
No problem.
you could also write a script to make the structure since you have all the mboxes.
@cleidigh
