### ISSUE TITLE
Mbox import is not stripping out mbox From lines resulting in invalid headers

### ISSUE THREAD

**Issue by riverar** [thunderbird/import-export-tools-ng#534]
## Steps to reproduce
1. Import [repro.mbox.zip](https://github.com/thunderbird/import-export-tools-ng/files/14288745/repro.mbox.zip)
2. Select message > More > View Source
3. Observe message contains outer mbox `From notifications@bugsnag.com Sat Feb 10 19:56:29 2024` line
4. Attempt to transfer this message to an IMAP server
5. Observe Thunderbird error:

```
The current command did not succeed. The mail server for account [...] responded:
header key contains invalid characters.
```

Removing the line manually (e.g. using Header Tools Improved) resolves the issue but not tenable for lots of messages.

## Meta
ImportExportTools NG v14.0.1
Thunderbird 115.7.0 (64-bit) / Windows

**Comment by cleidigh** [comment]
@riverar 
On 115.7 with Windows I am not able to reproduce the problem .
The single message imports fine with the expected headers.
Your example is a run of the mill mbox.

When you observe a raw message (ctrl-U) incorrectly shows the mbox From separator 
Note ietng does not strip the From it stays in the mbox files.

I was also successful at both a copy and move of the message to my imap server.
The error is from the interaction between than Thunderbird and your server, ietng is out of that.
@cleidigh

**Comment by riverar** [comment]
Are you saying the "From " line is not showing up in your raw message headers? (screenshot below)

![image](https://github.com/thunderbird/import-export-tools-ng/assets/475132/b795bc7d-1d32-4401-863a-7bf17fc8a94d)

IMAP results may vary, depending on strictness. I suspect some IMAP servers may just ignore invalid lines.

**Comment by cleidigh** [comment]
@riverar 
What you are looking at is the message in local folders. This is a Thunderbird view issue.
Thunderbird would strip the message going to the server. The mbox for the imap folder would also have the From header,but is not shown in view source.

I am surprised you have any issues given the normal looking message imports and copies ok.

Try copying an imap msg to LF then back.
@cleidigh

**Comment by riverar** [comment]
Ah. Can confirm with a simple draft, Thunderbird is sending the outer "From " line to IMAP servers; looks like this might be a core Thunderbird bug? 

```
55 OK IDLE
56 append "INBOX" (\Seen) "10-Feb-2024 19:56:29 -0800" {18143}
+ Ready
From notifications@bugsnag.com Sat Feb 10 19:56:29 2024
Date: Sun, 11 Feb 2024 03:56:29 GMT
Subject: [EarTrumpet] System.OutOfMemoryException in string.ReplaceInternal(string oldValue, string newValue):0
From: notifications@bugsnag.com
To: "Rafael Rivera" <111111@1111111111111.com>
Cc: 
Content-Type: multipart/mixed;
  boundary="----=c09b4a4451764e09-ae1e-e438d297f606"

------=c09b4a4451764e09-ae1e-e438d297f606

[... snipped for brevity ...]

56 BAD header key contains invalid characters
57 IDLE
```

**Comment by riverar** [comment]
Similar Thunderbird bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1741748

Thanks for your help @cleidigh! I think we can close this.
