### ISSUE TITLE
Import mbox from Apple Entourage file - Add CR line termination import support

### ISSUE THREAD

**Issue by RalfTimmer** [thunderbird/import-export-tools-ng#540]
I have an old Microsoft Entourage install on an Apple computer with lots of e-mails. I want to import these in TB on Windows.
I have created a Main Identity.rge file with Entourage. 
It is now on my Dropbox and I can access it from my Windows laptop. When I double click the .rge file I browse through the various folders similar to my Entourage folder structure. On the lowest level I see the mbox files.
I have installed IETNG.
Importing the mbox files is not working. When I select one I see the message 'Skip non-mbox file' and the import does nothing.
I have copied one of the mbox files into another directory and removed the mbox extension (I read somewhere this is necessary), but that does not help either. Same message: 'non-mbox file' 

Any tips how to get my Entourage e-mails into TB?

**Comment by RalfTimmer** [comment]
> @RalfTimmer I have zero awareness of Entourage so it's a matter of looking at one of the files. Do you have an mbox you could post or privately email me? @cleidigh

Yes, I can send you a file per e-mail. What is your private e-mail address?

**Comment by cleidigh** [comment]
@RalfTimmer 
Great.
test1@kokkini.net
@cleidigh

**Comment by cleidigh** [comment]
@RalfTimmer 
So Microsoft strikes again.
The mbox files are using a non standard line terminator.
The From message separators are supposed to end with \n or \r\n
These use only \r
This is why the import rejected them.
I can change the regex to accept this and it imports six messages.
I don't think I want to change the production version to do this, but I can make a test version that you can use on these files.
I would caution that there might be some parsing issues that this might have.
Do you want to try that?
@cleidigh

**Comment by RalfTimmer** [comment]
Hi Christopher,

Yes, I would like to try that!

Really appreciate you are looking into this.

NB I used a demo version of SysTools MBOX converter and they do read the mbox files without errors, so somehow other tools do support these incorrect separators.

Thanks,
Ralf

**Comment by cleidigh** [comment]
@RalfTimmer 
I'm still working on the From escaping regex.
I'm hoping I can get a reliable version that works with all variations.
@cleidigh

**Comment by RalfTimmer** [comment]
> @RalfTimmer I'm still working on the From escaping regex. I'm hoping I can get a reliable version that works with all variations. @cleidigh

Thanks!

**Comment by RalfTimmer** [comment]
Hi Christopher,
I performed a small test myself by replacing all CR (they are actually at the end of every line not only separating the From) with LF in the test file using Notepad++. This worked and I can import the test file in TB.
However this is very time consuming because even for a small file with only 6 messages as in the test mbox file it takes minutes to do the search and replace for 440K lines.
So I would really appreciate if you can provide an updated version of your mbox import that supports importing my mbox files.

NB On https://www.loginradius.com/blog/engineering/eol-end-of-line-or-newline-characters/#:~:text=Open%20any%20text%20file%20and,appear%20(%5Cr%5Cn) I read "Mac (up to 9): Older Mac OSs consider '\r' as a newline terminator but newer OS versions have been made to be more compliant with Unix systems to use '\n' as the newline.". So this probably explains the reason for the CRs in the mbox file.

**Comment by cleidigh** [comment]
@RalfTimmer 
Yes I saw the references to OSX-9 and prior using \r as a line termination.
This is actually much more problematic than might appear. Many Javascript string and regex functions are not compatible.
This was why I had to take time on the best and least invasive solution.
I decided to preprocess and transform the crs to a temp mbox and then process normally.
Please let me know your results.
https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.2/xpi/beta/import-export-tools-ng-14.0.2-b12-tb.xpi

@cleidigh

**Comment by RalfTimmer** [comment]
I just tested on 1 file and it works. I will try more files soon, but so far it looks like you solved the problem. Will let you know the results of importing the rest of my Entourage files. Thank you!

**Comment by cleidigh** [comment]
Great!
@cleidigh

**Comment by cleidigh** [comment]
@RalfTimmer 
Just wanted to check if you have converted any more files?
@cleidigh

**Comment by RalfTimmer** [comment]
@cleidigh Yes, I have imported all files and as far as I can see all went well. I randomly opened messages in various folders and it looks all good.
I had to import them one by one, because importing 'all files from directory' did not work.
Thank you again for providing me a solution. I can continue using TB and delete my Entourage instance!

**Comment by cleidigh** [comment]
@RalfTimmer 
Great. Yes, Thunderbird doesn't understand the rge structure.
Reviews are always appreciated on the addon site %-)
Glad we could get your old mail imported.
Christopher

**Comment by cleidigh** [comment]
@RalfTimmer 
Thanks for the very nice review!
@cleidigh
