### ISSUE TITLE
Attachment Limit

### ISSUE THREAD

**Issue by RJUPI** [thunderbird/import-export-tools-ng#551]
When I attempt to export 290k messages in text format with attachments, the process stops when the attachment filenames reach "Attachment-9999". Is there a way around this issue?

**Comment by RJUPI** [comment]
115.9.0 (64-bit)
Version 14.0.1
Windows 10

**Comment by cleidigh** [comment]
@RJUPI 
I'm literally days away from releasing v14.0.2. If I can identify this will try and include.

Two questions : 
When you hit 10k attachments does the export stop or just attachment output?
Can you capture the debug console output and post?
I don't have any test sets with 10k attachments so I am probably going to simulate. I'm guessing the old api may max out at 10k
@cleidigh

**Comment by RJUPI** [comment]
Sorry, I do not know how to capture the debug console output.

Just ignore me for now.
