### ISSUE TITLE
After last Update no more mail reception

### ISSUE THREAD

**Issue by MartinLehmann69** [thunderbird/import-export-tools-ng#558]
After getting the Mozilla Update with the Im-/Exportfunction Thunderbird refuses to receive any mail (without error message - simply don't get any more mails). :(
And this after 20 years of usage without any issue!

**Comment by cleidigh** [comment]
@MartinLehmann69 
Thanks for being a loyal user!
Sorry, this is a serious issue, but confounding as IETNG does no involvement in mail reception.
Can you give some more detail?
OS, TB versions also what errors do you see? Anything in the debug log?
@cleidigh

**Comment by MartinLehmann69** [comment]
Dear Christopher,TB=115.9.0 (64 bit)OS=Kubuntu 22.04Best rgds.Martin Am 18.04.2024 19:40 schrieb Christopher Leidigh ***@***.***>:
@MartinLehmann69
Thanks for being a loyal user!
Sorry, this is a serious issue, but confounding as IETNG does no involvement in mail reception.
Can you give some more detail?
OS, TB versions also what errors do you see? Anything in the debug log?
@cleidigh

**Comment by cleidigh** [comment]
Any info on errors or the log?
@cleidigh

**Comment by MartinLehmann69** [comment]
And the logfile says what's on the Screenshot in the attachment.Am 18.04.2024 19:40 schrieb Christopher Leidigh ***@***.***>:
@MartinLehmann69
Thanks for being a loyal user!
Sorry, this is a serious issue, but confounding as IETNG does no involvement in mail reception.
Can you give some more detail?
OS, TB versions also what errors do you see? Anything in the debug log?
@cleidigh

**Comment by cleidigh** [comment]
@MartinLehmann69 
Thanks, I don't see any screenshot or attachment though.
@cleidigh

**Comment by MartinLehmann69** [comment]
Just send a second Mail with a Screenshot of the Error.logAm 18.04.2024 20:00 schrieb Christopher Leidigh ***@***.***>:
Any info on errors or the log?
@cleidigh

**Comment by MartinLehmann69** [comment]
Sending from Handy ist Always a pain die me (using Googlemail instead of the really great Thunderbird;))Am 18.04.2024 20:08 schrieb Christopher Leidigh ***@***.***>:
@MartinLehmann69
Thanks, I don't see any screenshot or attachment though.
@cleidigh

**Comment by cleidigh** [comment]
@MartinLehmann69 
I think there is an issue with email and attachments. You can send to my test account.
test1@kokkini.net
@cleidigh

**Comment by cleidigh** [comment]
@MartinLehmann69 
Got it thanks.
The one conduit error is usually an artifact on shutdown.
What happens if you disable IETNG, does mail reception return? Then reenable and check log.
Do you have other extensions you can disable?
@cleidigh

**Comment by MartinLehmann69** [comment]
First screenshot was too big...send again...please ready belowAm 18.04.2024 21:31 schrieb ***@***.***:All Plugins disabled, Log ist clean now apart of the Network Error in the Last line of the First screenshotAm 18.04.2024 20:54 schrieb Christopher Leidigh ***@***.***>:
@MartinLehmann69
Got it thanks.
The one conduit error is usually an artifact on shutdown.
What happens if you disable IETNG, does mail reception return? Then reenable and check log.
Do you have other extensions you can disable?
@cleidigh

**Comment by cleidigh** [comment]
@MartinLehmann69 
It might be duplication, but can you close Thunderbird, restart and capture the log again?

If you are not receiving mail, do you get any more errors when you send email to yourself?
If you disable IETNG does that email get received?
Do IETNG menu and button functions work?
@cleidigh

**Comment by MartinLehmann69** [comment]
Good morning Christopher,here the logfile sending Mail to myselfMaybe there was something else in Thunderbird updated, too.Best rgds.Martin Am 18.04.2024 23:41 schrieb Christopher Leidigh ***@***.***>:
@MartinLehmann69
It might be duplication, but can you close Thunderbird, restart and capture the log again?
If you are not receiving mail, do you get any more errors when you send email to yourself?
If you disable IETNG does that email get received?
Do IETNG menu and button functions work?
@cleidigh

**Comment by cleidigh** [comment]
I didn't get the log file, maybe send to test address.
So when you disable IETNG does the email arrive?
@cleidigh
