### ISSUE TITLE
Random .eml files export sub folders

### ISSUE THREAD

**Issue by Thomas-AIRS-Informatique** [thunderbird/import-export-tools-ng#561]
Hello, when exporting all messages in .eml format (Messages, index, and subfolders) I am missing messages (the index is correct).
I tested several times with the following architecture:

Folder :
- Sub folder 1
   - mail.eml
   - mail1.eml
- Sub folder 2
   - mail.eml
   - mail1.eml
   - mail3.eml
- Sub folder 3
   - mail.eml
   - mail1.eml
   - mail3.eml
  - mail4.eml

The problem is that when I export (several times by deleting the last export) there are never all the .emls and with each export the number of .emls in a subfolder changes (on 140 .emls one suddenly it's 49 .eml the other is 57 .eml in the same subfolder) and this applies to the entire INBOX tree

sorry for my English
Thanks

**Comment by cleidigh** [comment]
@Thomas-AIRS-Informatique 
Thanks for the post, sorry for the issue.
No apologies on language, I'm sure I would be limited or toung tied in yours %-)

So first thing I would check is the export of a couple of folders individually, do they export correctly? After that, I probably have to do some debug beta for you.
@cleidigh

**Comment by Thomas-AIRS-Informatique** [comment]
Hello, Thanks for the feedback.
If I export a single folder everything goes well, I find all the contents.
On the other hand, with the option with export in.eml with subfolders created this problem for me (emails are missing randomly)

Currently the box is 70GB with sometimes 3 or 4 levels of subfolders.
The tree exports perfectly.

Do not hesitate to ask me if you need additional elements.

Thank you for your work in any case.

**Comment by cleidigh** [comment]
@Thomas-AIRS-Informatique 
Thanks for your support !
Ok the one comment I didn't understand is 

Currently the box is 70GB with sometimes 3 or 4 levels of subfolders.
The tree exports perfectly.

What do you mean by tree? That sounds like subfolders. What exports perfectly?
@cleidigh

**Comment by cleidigh** [comment]
@Thomas-AIRS-Informatique 
One more question : 
What if you export some subfolders to html or pdf?
There are some different approaches to each.
@cleidigh

**Comment by Thomas-AIRS-Informatique** [comment]
I am talking about the folder tree (the entire folder structure is correctly exported)
As for the other formats, things are going well.
Best regards
Thomas

**Comment by cleidigh** [comment]
@Thomas-AIRS-Informatique 
Ok so you are saying, structure ok, but missed emails in folders.
Also other formats export with subfolders complete.

I think I will work on debug and some tests.
@cleidigh

**Comment by cleidigh** [comment]
@Thomas-AIRS-Informatique 
I did some tests and more experiments over the weekend and found timing glitches over certain larger folders. I rewrote the changes done for subfolders.
I see a stable, consistent export now. It's also faster %-)
If you can try this beta that would be helpful.

https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.3/xpi/beta/import-export-tools-ng-14.0.3-b3-tb.xpi

Thanks 
@cleidigh

**Comment by Thomas-AIRS-Informatique** [comment]
Hello @cleidigh ,
Please excuse me, I was on leave.
I have just tested the b3 and b9 versions and the contents of the folders seem fine to me.
I just exported 120 GB of emails more than 80000 files

Thanks a lot for your help

**Comment by cleidigh** [comment]
Thomas 
No problem. 
Well you are officially the top export dog!!
120GB!
Excellent.
I have also just fixed the abort for subfolders. When I put that out can I trouble you for a test or two? It was more invasive than expected and I want to make sure I have enough other testers than myself 
Merci,
Christopher
