### ISSUE TITLE
No option to import MBOX folder (working on MAC)

### ISSUE THREAD

**Issue by Cherpet24** [thunderbird/import-export-tools-ng#563]
Hi.  I am working on a MAC.  I have watched dozens of tutorials but all seem outdated for this version of import-export-tools-ng.  I cannot find an option to import MBOX.  I have multiple MBOX folders to import into a gmail. 
1)  I imported one of them through Account Settings -> local directory -> chose the takeout folder 
those all imported.
<img width="1032" alt="Screenshot 2024-05-02 at 6 42 53 AM" src="https://github.com/thunderbird/import-export-tools-ng/assets/168740609/b92259d5-c5d3-419e-a2a2-81fd74146a2d">

However if I decide to go this route again  and choose a different mbox folder on the local directory, will it remove all the emails I already imported?

2) If I go the route you talk about with a R click (I am on a MAC and cannot R click) so go to tools up above, I have no option for import MBOX.  
<img width="1027" alt="Screenshot 2024-05-02 at 6 40 48 AM" src="https://github.com/thunderbird/import-export-tools-ng/assets/168740609/54436c02-aa26-4324-bf6e-ab203281024d">

I apologize in advance as I am only learning through video tutorials but hoping you can help me!!

**Comment by cleidigh** [comment]
@Cherpet24 
No apologies, there is never enough documentation. Unfortunately I can't do videos being disabled.
Most of the import and export functions are found in right click context menus.

For folder based operations you right click on a folder. Note for mbox import you have to import to a Local Folders folder, you can't import to imap.

Messages can be selected and The context menus have many options.
Don't hesitate to ask more...
@cleidigh
