### ISSUE TITLE
'File not found' Error

### ISSUE THREAD

**Issue by zensubz** [thunderbird/import-export-tools-ng#567]
Hi,

Thanks for your work on this great tool. I have run into a minor issue with the latest version v14.0.2. When I click on the bar-menu button I get the 'File not found' error. There is no such issue with the earlier version (v14.0.1). My tb version is v115.10.0. Other than this small issue, I am able to access the options/help via the right-click menu. Would appreciate if you could fix this. Thanks.

![impexp_error](https://github.com/thunderbird/import-export-tools-ng/assets/5127872/fe818c8d-ac47-4445-ab06-500d2af21565)

**Comment by cleidigh** [comment]
@zensubz 
Thanks for the post.
This is quite odd. The file definitely exists and I have no issues on Windows or Linux. What OS are you on. Can you capture the debug console output?
I might suggest a reinstall as one step.
@cleidigh

**Comment by zensubz** [comment]
@cleidigh, I forgot to mention the OS, it is CentOS 7.9. I followed your suggestions, uninstalled v14.0.1, and then installed v14.0.2 - but the problem still persists. I tried to get the debug console output; doing it for the first time, hope the following screenshots convey required info. Do let me know/guide me in case these are inappropriate. Thanks.

Debug console output for v14.0.1:
![toolbox_console_v14 0 1](https://github.com/thunderbird/import-export-tools-ng/assets/5127872/a72ac79d-d124-4718-8ec4-f646d6bf2c4b)

Debug console output for v14.0.2 (looks like XML parsing error):
![toolbox_console_v14 0 2](https://github.com/thunderbird/import-export-tools-ng/assets/5127872/9e11d5a4-b504-49b4-9a6e-2a89b0062cb7)

**Comment by zensubz** [comment]
@cleidigh, wanted to give a follow-up. After playing around with debugging using 'Tools->Developer Tools', followed by 'Debug Addons' via 'Add-ons Manager', now v14.0.2 seems to be working - the left-click menu (on bar) is working. But it doesn't open if I downgrade it to v14.0.1 as shown in the screenshots below:

v14.0.1:
![Selection_001](https://github.com/thunderbird/import-export-tools-ng/assets/5127872/724c5125-51cd-4e49-8a32-eb1a5b8d6738)
v14.0.2:
![Selection_002](https://github.com/thunderbird/import-export-tools-ng/assets/5127872/bc33a1d8-0464-4dc4-81d4-feae53b0d722)
In a way the issue may be sorted out, but would appreciate your opinion/suggestions in this regard. Thanks.

**Comment by cleidigh** [comment]
@zensubz 
Thanks for the follow up.
I had a bit of a hard time looking at your v14.0.2 debug screenshot, it would not expand for some reason. What I noticed were the two module versions. They show -3 when they should be -4 for v14.0.2.
I think there may have been a caching issue that finally got resolved.
I have some times seen it take two restarts of Thunderbird to get the addon ok.
Let me know if it misbehaves again.
@cleidigh

**Comment by zensubz** [comment]
@cleidigh, thanks for your kind clarifications. Now that v14.0.2 is working in all aspects, I would close this issue.

**Comment by kiki-ja** [comment]
Windows 10 Pro 22H2 64bit
Thunderbird 115.11.0 64bit
ImportExportTools NG 14.0.2 & 14.0.3b8

The reproduction procedure is as follows
1. Install ImportExportTools NG on Thunderbird
2. Left-click the IETNG icon on the toolbar immediately after installation.
Nothing is logged in the error console.

Workaround:
Restart Thunderbird and this problem will not occur.

@kiki-ja
