### ISSUE TITLE
Is MailDir support still available in T'Bird?

### ISSUE THREAD

**Issue by Budgie2** [thunderbird/import-export-tools-ng#570]
A few years ago and with the intention of being safer I backed up older messages using both MBox and Maildir using Thunderbird import-export-tools-ng?

Is Maildir method still supported?  I have only just installed the addon and do not see the Maildir or maildir-lite option offered.

Also is there any documentation available?

**Comment by cleidigh** [comment]
@Budgie2 
The short answer is yes, both Thunderbird and IETNG support MAILDIR. The functionality is not as extensive as mbox.

Basically you can import a maildir folder by right clicking on a folder in a maildir account. Go to ietng.
You can also export a maildir folder to mbox.
@cleidigh
