### ISSUE TITLE
Worked once, then disappeared

### ISSUE THREAD

**Issue by Broomholm** [thunderbird/import-export-tools-ng#574]
I am not a Techie, so be patient..
Running Win-10.  Trying to  move archived mail folders from Pegaus Mail to Thunderbird.  Figured out how to get Pegasus to create .MBX files.  Installed ImportExportTools in Thunderbird. Clicked on "ImportExport" in menu bar, (Is that the correct term??  -the bar at the top of the window...).  Got a nice drop down with choices to import files.  Chose .mbox, and it worked flawlessly.  But now I am unable to figure out how I did it - the drop down menu has only 3  choices: Import Profile; Export Profile; and Backup, plus Options and Help.  I cannot find the choices for importing files, nor can I find it in either Tools, or the hamburger menu, (other than the original Import tool in Thunderbird, which doesn't work for .mbox files, (which is why I installed ImportExportTools-ng in the first place.  What have I done wrong?

**Comment by cleidigh** [comment]
@Broomholm 
Thanks for using ImportExportTools!

- The ImportExport button on the toolbar is for independent operations, backup/profiles
- Folder operations are found by right clicking a folder, mbox ops here 
- Message operations on selected messages, right click on selected messages 

The help will give menu items, but some not updated.
Note, import of mbox files must be done to a local folder

Let me know if this helps
@cleidigh

**Comment by Broomholm** [comment]
Got it!  The trick is to go from a specific item in the Folders menu in TB, Right click, (which brings up a cascading menu, at the end of which is "Import Mbox files", and Bingo!  Thank you so much.

**Comment by cleidigh** [comment]
Great!
