### ISSUE TITLE
Exporting messages with illegal filename characters fails - v14.1.0-b2 fix 

### ISSUE THREAD

**Issue by lkintact** [thunderbird/import-export-tools-ng#576]
Hi! 
If I have an IMAP folder with any of theese - `|`, `*`, `:`, `<`, `?`, `\`, `"` - characters in its name, none of the `Export All Messages In Folder` commands work correctly: ImportExportTools NG just creates an empty directory (replacing the listed chars with a `_`).
FWIW, the `Folder Export (mbox)` commands do work.

OS: Windows 10 Home
Thunderbird: 115.11.1 (64-bit)
ImportExportTools NG: v14.0.2.

**Comment by lkintact** [comment]
> FWIW, the Folder Export (mbox) commands do work.

As I just discovered, they do not work if the folder you want to export contains subfolders having the aforementioned chars in their names.

**Comment by cleidigh** [comment]
@lkintact 
Ugg, yes you are correct, I just confirmed your observation.
And I missed this with v14.0.3just in the review Q, damn it %-{
I am working on beta for Thunderbird 128/115 so I will fix it there and post here:
- #575 
 and notify you  here.
Thanks for catching this, shame it was not a couple of days earlier.
@cleidigh

**Comment by cleidigh** [comment]
@lkintact 
The issue with Export all messages in folder is a missing filter for illegal characters. This is clear and I can show the fix works.

I cannot, however, see any problem with Folder Export (mbox)
Both individual and with subfolders export at all levels with illegal characters substituted with the underscore.
This is a different code path and has the substitution code.

So I am confused by what you are seeing with respect to mbox exports. Can you capture the debug console output?
Thanks,
@cleidigh

**Comment by lkintact** [comment]
@cleidigh Sorry, I was wrong: all the four `Folder Export (mbox)` commands do work.
Thank you for answering and your work!

**Comment by cleidigh** [comment]
@lkintact 
Great, i was worried for a bit...
I will have a beta patch tomorrow.
@cleidigh

**Comment by cleidigh** [comment]
@lkintact 
Just posted v14.1.0-b1 with the fix for the missing illegal character filter.
Any testing you can do would be great.
- #575 

@cleidigh

**Comment by cleidigh** [comment]
@lkintact 
This is a github quirk.See:
https://github.com/cleidigh/printing-tools-ng/issues/154
@cleidigh

**Comment by lkintact** [comment]
Just finished testing. I created an IMAP folder `folder | * : < ? \ "` containing several messages and a subfolder `subfolder | * : < ? \ "`, also with messages inside; tried all the `Export All Messages In Folder` commands ending with `with Subfolders` on it, also tried the `CSV Format (Spreadsheet)` command and both `Message Index` commands. Everything seems to works.

**Comment by lkintact** [comment]
>  Btw, are you a bleeding edge person, are you using 128 beta or planning to move to 128 quickly?
Sorry, I'm not, but I will be glad to help in any way I can.

**Comment by cleidigh** [comment]
@lkintact 
No problem, you are already helping as v14.1.0 branch is now common for both 128 & 115.
Hence the new converter issue you also just posted.
Christopher
