### ISSUE TITLE
MacOS doesn't preview with thumbnails or quicklook all mails exported as eml

### ISSUE THREAD

**Issue by andreamoretti** [thunderbird/import-export-tools-ng#579]
Since Catalina, MacOS doesn't preview with thumbnails or quicklook all mails exported as eml. I solved the problem using dos2unix ([link](https://dos2unix.sourceforge.io/)), but one by one...
Is there a way to export mails in a UNIX compatible format?

Thanks in advance

Andrea Moretti

**Comment by cleidigh** [comment]
@andreamoretti 
Yup.
Use the strip CR from eml exports option on the Misc tab.
@cleidigh

**Comment by andreamoretti** [comment]
@cleidigh thank you! Problem solved!
