### ISSUE TITLE
Message files are prepended with ï»¿ when exporting messages - v14.1.0-b2 fix

### ISSUE THREAD

**Issue by lkintact** [thunderbird/import-export-tools-ng#581]
Perform any of the four `Export All Messages In Folder` > `HTML Format` commands on an IMAP folder containing messages. The HTML message files that IET NG creates have `ï»¿` (when viewed in UTF-8) at the beginning.

OS: Windows 10 Home
ImportExportTools NG: 14.1.0-b1.

**Comment by cleidigh** [comment]
@lkintact 
Thanks 
Fixed in b2
- #575 

Fix, break...
Christopher

**Comment by cleidigh** [comment]
@lkintact 
Just checking if you were able to verify the fix in b2?
@cleidigh

**Comment by lkintact** [comment]
Yeah, the bug is gone for me in beta 2, thanks!

**Comment by cleidigh** [comment]
Thank you much!
Are you already using Thunderbird 128 beta?
I'm trying to id beta users to make sure I can release on time.
All testing very much appreciated!
Christopher

**Comment by lkintact** [comment]
> Are you already using Thunderbird 128 beta?
Nope, my Thunderbird is "currently on the esr update channel", so no.

**Comment by cleidigh** [comment]
Thanks
