### ISSUE TITLE
LF instead of CRLF upon exporting messages as plain text - v14.1.0-b3 fix 

### ISSUE THREAD

**Issue by QbaMi** [thunderbird/import-export-tools-ng#584]
Hi,

It seems that since version 14.0.3 there has been an unexpected change in how plain text export is handling line breaks.
So far the messages were exported with CRLF line breaks, but now I get LF.
I don't know if it was intended, as I didn't found that being mentioned in change log. Could be a bug?
I've went through the files changed in [v14.0.3](https://github.com/thunderbird/import-export-tools-ng/pull/577/files#top) and in [src/chrome/content/mboximport/exportTools.js](https://github.com/thunderbird/import-export-tools-ng/pull/577/files#diff-5753f0c9eabaadcfa95ece05922797579538920f2d3f9dc8df0d8fad77211a93) noticed that special tretment, in regards to CRLF, was introduced for Windows 7. I'm working on Windows 10, so my setup should have been unaffected, but still I get different results.

Would appreciate any advice on the topic.

OS: Windows 10
ImportExportTools NG: 14.0.3
Thunderbird: 115.11.1 32-bit

**Comment by cleidigh** [comment]
@QbaMi 
Thanks for the post. I have several issues that relate to this that were related to text conversion heading into the 128 release. I will check this out and I can address it in the next beta.
@cleidigh

**Comment by cleidigh** [comment]
@QbaMi 
Fixed in b3 beta (for 115 &128)
- #575 
- @cleidigh

**Comment by cleidigh** [comment]
@QbaMi 
Just wanted to verify if you were able to test and confirm this was resolved.
@cleidigh
