### ISSUE TITLE
To, From and ReplyTo fields show names, not email addresses (html, plaintext) - v14.1.0-b4 fix 

### ISSUE THREAD

**Issue by sallyscarlett** [thunderbird/import-export-tools-ng#586]
On version 14.0.3 ImportExportTools NG running on Thunderbird 115.10.1 on MacOS 11.7.6, when I export to plain text, then the email addresses are not showing in the resulting file.  

E.g.  it looks like this:
From: Sally Houghton
Date: 2024-06-19, 2:27 p.m.
To: Liz Brown

whereas before it was (email addresses changed for privacy reasons):
From: Sally Houghton <sally7001@gmail.com>
Date: 2024-02-19, 8:31 p.m.
To: Liz Brown <liz9001@gmail.com>

It is okay when saving as PDF, so I have a work-around, but I liked saving as text, as PDF just saves the email and not the attachments.

**Comment by sallyscarlett** [comment]
Exploring a bit more, it is not consistent missing all email addresses.  For example when multiple on the to/cc line, they come through okay.  But will never get the from address as that is always a single address

**Comment by cleidigh** [comment]
@sallyscarlett 
I'm looking at what happened because on Thunderbird v115 Somewhere along the way this changed. I go back to the long, stable v14.0.1 with the same result. So I have to figure out what they did.
@cleidigh

**Comment by sallyscarlett** [comment]
That will teach me for upgrading thunderbird :-0

Thanks for looking at it!

**Comment by cleidigh** [comment]
@sallyscarlett 
Well it's a consequence of a legacy addon which requires low level access.
I'm working on the update for v128 so hopefully I can have a beta fix shortly.
@cleidigh

**Comment by sallyscarlett** [comment]
Awesome - thanks so much!

**Comment by cleidigh** [comment]
@sallyscarlett 
I have this fixed in b4. I still saw one oddity with replyto, however, this was only once so don't know what to make of that.
Grab here: 
- #575 

@cleidigh

**Comment by sallyscarlett** [comment]
thanks - pardon my ignorance -- but is there a page on how to install an xpi file?

**Comment by cleidigh** [comment]
@sallyscarlett 
Download the file 
Go to the Add-ons tab
Click the gear and choose Install Add-on from file
Pick the download 
@cleidigh

**Comment by sallyscarlett** [comment]
Thanks for fixing this so quickly - works like a charm!

**Comment by cleidigh** [comment]
@sallyscarlett 
Excellent.
I keep these open until I actually release the fix.
BTW, reviews on the addon site are always welcome %-)
@cleidigh

**Comment by sallyscarlett** [comment]
Done :-)

**Comment by cleidigh** [comment]
@sallyscarlett 
Very, very nice review.
And thanks for the donation!
💯 
Christopher

**Comment by sallyscarlett** [comment]
More than welcome -- I only use two add-ons and the other (mail merge) is very infrequently.  I use this add-on all day, every day -- love it :-)
