### ISSUE TITLE
No index created in ja, zn-CH locales, bad localization pointers - v14.1.0-b5 fix

### ISSUE THREAD

**Issue by cleidigh** [thunderbird/import-export-tools-ng#588]
The localization file pointers are wrong.

@kiki-ja
This was a really stupid one!
The pointers go to printingtools...Bad and stupid!!
What I don't get is why no ja users have not raised this issue?? Ja locale users are the largest group??
Actually I don't even remember the last issue from a ja user, isn't that odd?
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

>The localization file pointers are wrong.

I don't know, so it is difficult for me to comment.
Is the wrong pointer in question the 'headerFields.ftl' if it is IETNG?

>What I don't get is why no ja users have not raised this issue??

I only know the difference between the header in the message pane and the message header when printing.

e.g
・Message pane header: From = 差出人 (ja)
・Print header: From = From (not ja)

@kiki-ja
