### ISSUE TITLE
Context Menus Not Showing

### ISSUE THREAD

**Issue by pacolvin** [thunderbird/import-export-tools-ng#589]
I am having a similar issue as #587 with two menu entries, but I can only see the following menu items:

Export Profile>
Import Profile
Backup
Options
Help

I do not have any message and folder context menus showing.

Thunderbird 115.21.1
MacOS 14.5

**Comment by cleidigh** [comment]
@pacolvin 
As you saw the doubleTools menu has been reported as a Thunderbird bug.
Now when you say you don't have the folder or message context menus, you are saying that when you right click on a folder or message the ImportExportTools icon/menu does not show in the popup menus?
@cleidigh

**Comment by pacolvin** [comment]
Yes, this was my error. I do see the folder and message menus when I right click. I thought they would be in the main Tool menu.

Thanks

Phil

**Comment by cleidigh** [comment]
@pacolvin 
Yes since they operate on selections they are on the context menus.
I will go ahead and close.
cheers,
Christopher
