### ISSUE TITLE
Problems with Copy To Clipboard 	> Message - v14.1.0-b7 fix

### ISSUE THREAD

**Issue by ayoogh** [thunderbird/import-export-tools-ng#594]
Hello

In bug issues, include the following information to help solve the issues:
- ImportExportTools NG version : Version 14.0.3
- Thunderbird version : 115.12.2 (64-bit) Portable 
- Operating system and version : Windows 10 Pro (64-bit) 22H2 (10.0.19045 Build 19045)
- Debug output (copy from the Debug Console - access with Control-Shift-J) - please see Debug output  10_13 Fri 05 Jul  2024.rtf in zip file enclosed
- A description of the steps leading to the issue:
I regularly use the Copy To Clipboard > Message facility to make a  ext copy of messages for my records and in the past it has always worked perfectly. Recently however the function copies a lot of  information that look like headers ( please see fri 05 jul 24 - Copy To Clipboard - Message.rtf in zip file) rather than just the usual  copied message - similar to this forwarded to another Thunderbird installation and copied to clipboard > message:

Subject: Re: testing ImportExportTools NG
From: email
Date: Fri 05 July 2024, 12:30
To: email
CC: enail

testing

From: email
Sent: Friday, July 05, 2024 11:29 AM +10
To: email account

Subject: email 
Fri 05 July  2024 11:20
Testing ImportExportTools NG
Message Context Menu
Copy To Clipboard 	
Message 	Copy a single selected message to the clipboard
Headers 	Copy the headers of a single selected message to the clipboard
Virus-free.www.avast.com

Not sure what is causing this  to occur but I also notice that this installation has Copy to Clipboard by itself at the bottom of the right click context menu whereas with the problematic  one it is under Export Message as.. > Copy to Clipboard > Message.

---
Also  I opened the ImportExportTools NG Help v14.0.3 file and would like to save it to my desktop but in File > Save as > File.. Control+S is disabled (greyed out), Is there a way to copy this to location on my computer?

Thank you for your help and assistance

[ImportExportTools NG Issues.zip](https://github.com/user-attachments/files/16104460/ImportExportTools.NG.Issues.zip)

**Comment by cleidigh** [comment]
@ayoogh 
Just saw your post before getting to bed so I have not analyzed.
I fixed a number of issues related. Can you check my latest?
https://github.com/thunderbird/import-export-tools-ng/issues/575
Install with the gear icon on the addons tab.
If the problem still remains, please let me know ASAP because I am days away from this release.
Thanks 
@cleidigh

**Comment by ayoogh** [comment]
Thank you @cleidigh for your prompt attention and reply. Have a good night's sleep with sweet dreams a plenty.

Not having any luck with installing the import-export-tools-ng-14.1.0-b4-tb.xpi.  Tried it several time but always get This is the message:

![corrupt addon](https://github.com/thunderbird/import-export-tools-ng/assets/18418309/a582b252-93dc-43bb-868d-3191b0e3ec59)

**Comment by cleidigh** [comment]
@ayoogh 
This is a weird issue with github. See if the note below helps:
https://github.com/cleidigh/printing-tools-ng/issues/154
If not send me an email to : 
test1@kokkini.net
and I will send a dropbox link.
@cleidigh

**Comment by cleidigh** [comment]
@ayoogh 
Also just posted b5 which fixes export error I introduced for v115
@cleidigh

**Comment by cleidigh** [comment]
@ayoogh 
Ok b5 as zip
[import-export-tools-ng-14.1.0-b5-tb.zip](https://github.com/user-attachments/files/16112236/import-export-tools-ng-14.1.0-b5-tb.zip)
@cleidigh

**Comment by cleidigh** [comment]
@ayoogh 
It's not a good day. B5 suddenly breaks.
Hopefully I can get back what I had, something odd.
@cleidigh

**Comment by ayoogh** [comment]
Hi @cleidigh, thanks again.

Downloaded  import-export-tools-ng-14.1.0-b5-tb.xpi as per your cleidigh/printing-tools-ng#154 instructions and installed it but the Export Message as.. > Copy to Clipboard > Message still copies what seems like both headers and the message rather than just the message by itself in plain text, please see the ImportExportTools NG Issues\fri 05 jul 24 - Copy To Clipboard - Message.rtf file in the zip file I sent for an example of what I mean.

BTW it looks like in your zip file you may have omitted to include the xpi file. this is the contents of the zip file I downloaded:
![zipcontent](https://github.com/thunderbird/import-export-tools-ng/assets/18418309/a6c57399-01ca-45eb-b146-f9242bf4c591)

Cheers.

**Comment by cleidigh** [comment]
Hmm, very odd. Does this happen with all messages?
I have checked and rechecked, cannot reproduce.
I will have to do some debug I guess. I also have another user who uses
copytoclip also with no issues so this is odd.
@cleidigh

**Comment by cleidigh** [comment]
@ayoogh 
I didn't answer two of your questions : 
For printing help - Use File/Print

The zip I posted is just a renamed xpi which is a zip file but can't post as xpi.

As I asked about other messages, I am wondering about the format. 
However, you have been doing this before so there has to be something different with my changes, just don't know why you and not others are seeing this.
Anyway I am adding debug now and will post in an hour or so.
@cleidigh

**Comment by cleidigh** [comment]
@ayoogh 
Ok posted b6
- #575 

I did notice two things in your rdf.
First the headers start with From -
That should never be in a message, that's a Thunderbird potential issue.
In the rdf I also don't see any line breaks.

Couple questions : 
Can you try with a few different messages.
Disable all other addons, restart, try again.
Try to copytoclip on a couple of messages in a local folder.

See if the console has a good example of the problem with my added debug And post as a text file, not rdf.

I also would try turning off avast, send yourself an email and check that.

Finally, I don't get the double menu entries, does that do anything?
@cleidigh

**Comment by cleidigh** [comment]
I think I found the problem. It looks like the api returns headers with messages in a local folder.
I'm trying a completely different approach so don't bother doing anything until I redo it.
@cleidigh

**Comment by ayoogh** [comment]
Hello,

I thought that it might be better to start afresh rather than mucking around the old installations  with a new email provider and address and this is the result:

Brand new, fresh Tbird Portable 115.12.2 (64-bit) installation
Thunderbird, Portable Editionportableapps - 1.0
-----------------------------------------------------------------------------------------

NG v14.1.0-b6 installed > Not working
Copy of message; Testing ImportExportTools NG v14.1.0-b6 14:18 Sun 07 Jul 2024 14:17
Testing ImportExportTools NG v14.1.0-b6 installed
- 
This email has been checked for viruses by Avast antivirus software.
www.avast.com

-----------------------------------------------------------------------------------------

NG - v14.1.0-b5 14:06  > Not working
import-export-tools-ng-14.1.0-b5-tb.xpi

Copy of message; Testing ImportExportTools NG v14.1.0-b5 14:06
Sun 07 Jul 2024 14:06

ImportExportTools NG v14.1.0-b5 installed
-- 
This email has been checked for viruses by Avast antivirus software.
www.avast.com

------------------------------------------------------------------------------------------------------------

NG v14.0.0 installed > Working as below

Subject: Testing ImportExportTools NG
From: impexptoo <impexptoo@gmx.co.uk>
Date: Sun 07 July 2024, 13:55
To: impexptoo@gmx.co.uk

Sun 07 Jul 2024
ImportExportTools NG v14.0.0 installed
	Virus-free.www.avast.com

-----
So avast is not the problem, rather a change/alteration introduced between NG v14.0.0 and later ones  that is likely to be causing the issue,

Hope  this helps - good luck with sorting it out.

**Comment by cleidigh** [comment]
@ayoogh 
Sorry for so much back and forth...
So going back to some of the old approach deals with both imap and LocalFolders messages. B7 should put this in good shape.
See
- #575 

@cleidigh

**Comment by ayoogh** [comment]
@cleidigh >  B7 should put this in good shape.

It certainly has.  
Thank you for sorting this out so quickly, efficiently and effectively,  
So much easier than copying the message after pressing the Reply button,

Time to explore more functions your fantastic Add-on has to offer.

All the best.

**Comment by cleidigh** [comment]
@ayoogh 
Thank you for your kind compliments!
Glad you caught this before the release.
Cheers
Christopher
