### ISSUE TITLE
Minor issue: Translation omission?

### ISSUE THREAD

**Issue by DenB10** [thunderbird/import-export-tools-ng#599]
@cleidigh 

Hi Christopher,

How are you?
I'm keeping a close eye on future version 14.1.0. As for the translation, I can see that you're doing just fine without my help...

However, when exporting as plain text or HTML, all headers are translated except "Reply-to". An oversight?

On the other hand, I've made a few tweaks to the French translation as PR, but I've made some mistakes which I'll point out below:

- In the messages.json file, penultimate entry: omission of the word "pas" : 
        `"multipleFolders.alertMsg": {
		"message": "L’exportation de plusieurs dossiers n’est pas possible.\nEn cliquant sur OK, seul le premier dossier sera exporté."
	}`

- In the importexport-help.html file, fifth release note:
        `- Correction : champs « De », « Pour » et « Réponse à » dans les exportations en HTML et texte brut (#586)<br>`

With apologies, greetings,

@DenB10

**Comment by cleidigh** [comment]
@DenB10 
How are you, thanks for tracking along!
I think you say merging your fr translation tweaks.
Yes the replyto was an intentional punt for now as I need to get the complete set of header translations pulled in that have become unavailable to addons. Since I am already overdue I just have to get it out.
@cleidigh

**Comment by cleidigh** [comment]
Sorry I missed your corrections. Will have to do later...

**Comment by DenB10** [comment]
No matter I'm the one who's sorry. I probably should have redone new PRs, it would have been easier.

**Comment by cleidigh** [comment]
Done
Merci!
