### ISSUE TITLE
Thunderbird Nebula Vers. 128.0

### ISSUE THREAD

**Issue by Eugen351** [thunderbird/import-export-tools-ng#600]
Unfortunately, import-export is not supported in this version. When will a compatible solution be released?

**Comment by cleidigh** [comment]
@Eugen351 
@GerryT11
I am releasing to the review Q tomorrow. If you want you can try the release beta here:
https://github.com/thunderbird/import-export-tools-ng/issues/575
Cheers
Christopher

**Comment by librelegal** [comment]
Hi, I know I am late to the party, but was not able to get b9 for testing here https://github.com/thunderbird/import-export-tools-ng/issues/575

**Comment by cleidigh** [comment]
@librelegal 
No problems.
I miss posted b9 as b8.
Anyway just released v14.1.0
I'm beat...

**Comment by librelegal** [comment]
Thank you very much. At the moment I am unable to find it, though. Unhappy to read you're beat. Please remember you own possibilities and do not to more than you really can. Am thankful for all your wonderful work.
