### ISSUE TITLE
Character Coding

### ISSUE THREAD

**Issue by ha-kg** [thunderbird/import-export-tools-ng#611]
I have some messages in Thunderbird which I want to export to htm.
The messages have German and French special Characters.
I tried UTF 8 and ISO 8859-1 but did not get the correct text.
Has anybody an idea which coe I shoild yous
Thank you
Hartmut
example:
Original in Thunderbird
Vom kostenlosen Großparkplatz auf der Île de la Barthelasse, einer 700 Hektar großen Flussinsel in der Rhône, pendeln kostenlose Shuttlebusse zur Porte de l’Oulle. Hinter dem betriebsamen Einfallstor zur Altstadt öffnet sich die Place Crillon mit zahlreichen Straßencafés im Schatten der Ancienne Comédie d’Avignon, die 1732 als erste Bühne der Stadt errichtet worden war – vorher hatte es in Avignon keinen eigenen Theaterbau gegeben

Text shown in the htm File
Vom kostenlosen Gro�Ÿparkplatz auf der �Žle de la Barthelasse, einer 700 Hektar gro�Ÿen Flussinsel in der Rhône, pendeln kostenlose Shuttlebusse zur Porte de l�€™Oulle. Hinter dem betriebsamen Einfallstor zur Altstadt öffnet sich die Place Crillon mit zahlreichen Stra�Ÿencafés im Schatten der Ancienne Comédie d�€™Avignon, die 1732 als erste Bühne der Stadt errichtet worden war �€“ vorher hatte es in Avignon keinen eigenen Theaterbau gegeben.

**Comment by cleidigh** [comment]
@ha-kg 
What Thunderbird, os and IETNG versions?
I just did a lot of work on this issue  for the latest release.
@cleidigh

**Comment by ha-kg** [comment]
Sorry, just checked that the new 14.1.2 is working well.
My update was to Standard
Hartmut

**Comment by cleidigh** [comment]
@ha-kg 
Great, i was worried after so much work on this.
Note html is always exported as utf8
The charset selector is only for text files.

**Comment by cleidigh** [comment]
@ha-kg 

Thanks for your donation and support!
Closing.
