### ISSUE TITLE
Does IETNG import attachments and embeddeds from mbox to TBird?

### ISSUE THREAD

**Issue by uispmatthews** [thunderbird/import-export-tools-ng#618]
I am converting from Eudora to Thunderbird by first running EudoraRescue to convert Eudora .mbx+.toc files to .mbox files in preparation for then importing them into Thunderbird. The resulting mbox files do not contain any MIME-encoded associated attachments but do contain full path links to them.

I note in my latest version of IETNG that under its options menu I can set the full path to both attachments and to embedded images and so assumed that IETNG would use these to suck the attachments listed in the mbox files into the resulting TBird mailboxes in its usual MIME encoding. However this does not happen. The body text comes in OK but not any attachments nor embedded images. 

Have I missed something, or am I too hopeful? 

Otherwise I guess I'll have to try Aid4Mail, systools, or a very early version of TBird that can import direct from Eudora.

Regards,
Peter Matthews

**Comment by cleidigh** [comment]
@uispmatthews 
I don't have any direct experience with Eudora, however, I have helped various users with moving Eudora messages to Thunderbird.
That said mbox files are a collection of RFC822 (eml) messages. These messages and the mbox can contain both the body and attachments together. Thunderbird and IETNG mboxes have theese together.
So my first thought is maybe the export from Eudora is stripping the attachments before exporting to mbox.
If The mbox files have messages with attachments they will be imported.
Perhaps Eudora has an option to include or not include attachments?

The separate attachment directories you see in options are for exports to formats that do not combine body+attatchments like html or plaintext. Eml and mbox exports always have attachments combined.
@cleidigh

**Comment by uispmatthews** [comment]
Thanks for your prompt response, Christopher. Appreciated.

Eudora does not store attachments nor embedded images in the message in its .mbx message files. Instead, upon receipt of a message it always extracts the attachment(s) into an attachments directory, from which they can be opened by clicking on a link at the bottom of the message when it is opened in Eudora. Embedded images will automatically show in the displayed message after auto-retrieval from the \embedded directory. There does not seem to be any message export function except per-message to text or html files that do not contain the attachments encoded within them (the html file does have a link to the attachment).

OK, so I'll explore using one of the three other methods that I listed in my original post.

Maybe you can add base64 encoding attachments and embedded images in a future import enhancement.

Thanks again.

Peter
