### ISSUE TITLE
How to Move Yahoo Mail folders to another Yahoo Account?

### ISSUE THREAD

**Issue by jackera1111** [thunderbird/import-export-tools-ng#619]
If you are looking for a solution to transfer folders from one Yahoo to another then I would recommend you use **Advik Yahoo Backup tool** on your system. The software can directly [export email folders from Yahoo to another Yahoo account](https://www.adviksoft.com/blog/export-yahoo-mail-folders-to-another-yahoo-account/). It preserves all email attributes and folder hierarchy as well during the migration. It is able to transfer complete mailboxes at once without any data loss. You can download its free version to check its working process.

**Steps to Transfer Yahoo Folders to Another Yahoo**

1. Run the tool on your Windows.
2. Choose Yahoo Mail and enter its login details.
3. Select the email folder you want to migrate.
4. Choose Yahoo Mail as a saving option.
5. Enter another Yahoo Mail login details and hit the Backup button.
The software will start transferring email folders from one Yahoo to another. 
![yahoo-to-yahoo-1 (2)](https://github.com/user-attachments/assets/6d783d65-b2a8-4a2e-9c0b-532187600dce)

**Comment by AlbertTaylor** [comment]
**[Shoviv IMAP to IMAP Migration Tool](https://www.shoviv.com/imap-to-office-365.html)** is a powerful solution for transferring emails between IMAP accounts, including Yahoo Mail. It allows you to easily migrate emails from one Yahoo account to another, preserving their original structure and content.
