### ISSUE TITLE
Allow the user to choose which service fields to save in Plain Text Format

### ISSUE THREAD

**Issue by Korb** [thunderbird/import-export-tools-ng#634]
Currently, when saving emails in Plain Text Format, a huge amount of service information is saved:

- Authentication-Results
- Content-Type
- Delivered-To
- DKIM-Signature
- In-Reply-To
- Message-ID
- MIME-Version
- Received
- Received-SPF
- References
- Return-Path
- X-Gmail-Fetch-Info
- X-Google-Smtp-Source
- X-Mailer
- X-Mozilla-Status
- X-Mozilla-Status2
- X-Received
- X-Yandex-FolderName
- X-Yandex-Forward
- X-Yandex-Front
- X-Yandex-Sender-Uid
- X-Yandex-Spam
- X-Yandex-TimeMark
- ...

It makes reading saved messages much more difficult. Especially since these documents are intended for reading only, not for import. In 99% of cases, basic information is enough for me:

1. Attachment Status
2. Bcc
3. Date
4. From
5. Priority
6. Subject
7. To
8. Сс

I suggest considering the possibility of exporting technical information about letters in abbreviated form, and only the fields present in the letter. _That is, for example, Bcc should not be included in the export if the corresponding field is missing in the letter, or it is empty._

**Comment by cleidigh** [comment]
@Korb 
Exporting to plaintext has always only exported Subject, From, To and date.
I just checked Thunderbird v128.2.0 on Windows and that still is the case.
Can you indicate os, tb and ietng versions?
Definitely should not be seeing all the headers.
@cleidigh

**Comment by Korb** [comment]
Microsoft Windows 10.0.19045.4894
Mozilla Thunderbird 128.2.0esr (64-bit)
ImportExportTools NG 14.1.2 (September 14, 2024)

**Comment by cleidigh** [comment]
@Korb 
Does this happen with all messages in all folders?
What does an html export look like?
@cleidigh

**Comment by Korb** [comment]
@cleidigh, same:

![2024-09-21_12-51-31](https://github.com/user-attachments/assets/e255a842-0081-447d-9197-5df25b584941)

Also, I visually compared the results of saving messages using the built-in function "Save As..." and "Export Messages As..." / Plain Text Format / Messages Only (and / HTML Format / Messages Only) and found no differences.

**Comment by cleidigh** [comment]
@Korb 
Have you tried with a fresh profile?
I can't think why the full set of headers is showing.
@cleidigh

**Comment by cleidigh** [comment]
@Korb 
Have been on hiatus...
Did you check the view headers option. If all is selected it would explain the extra headers.
@cleidigh

**Comment by Korb** [comment]
@cleidigh, I don't have the opportunity to check your proposal now. Let's close this issue now, and open it if it becomes relevant for someone again?

**Comment by cleidigh** [comment]
Ok
