### ISSUE TITLE
Problem on importing multiple EML messages from directory

### ISSUE THREAD

**Issue by ch3-coo** [thunderbird/import-export-tools-ng#635]
When I use ImportExportTools NG to import multiple EML messages from a directory, the messages are imported so that each message contains all the following ones (in the order in which they are imported) as text in their bodies.
That is, the first message contains its own text as well text and meta data of all the other messages in the message body, the second contains its own text as well as text and meta data of all the other messages except the first in the message body, and so, until the last, which is the only one properly imported, with just its own text in the body, basically.
So it's sort of importing messages like Matryoshka dolls...

- ImportExportTools NG v14.1.2
- Thunderbird 128.2.0
- Ubuntu 24.04.1 LTS

**Comment by cleidigh** [comment]
@ch3-coo 
This is probably the known issue with eml importing.
My b3 beta should do the trick.

https://github.com/thunderbird/import-export-tools-ng/blob/v14.1.3/xpi/beta/import-export-tools-ng-14.1.3-b3-tb.xpi

@cleidigh

**Comment by ch3-coo** [comment]
Indeed, that solves the problem.
Sorry I did not realize that previously posted issue was essentially the same.
Thanks a lot for the quick reply, the fix, and the useful add-on to begin with!
