### ISSUE TITLE
Export to PDF No Longer Working

### ISSUE THREAD

**Issue by JF1313** [thunderbird/import-export-tools-ng#636]
I'm running Version 14.1.2 : Maintenance Release - July,22 2024

I have ImporatExportTools NG convert emails to PDF files based on certain filter parameters.

Today I noticed that an email that fits a filter profile runs, the message is marked as read, BUT the email is not converted to PDF

When I manually run ImportExportTools NG on the same email a PDF is created and placed in the proper directory. I've reset the location several times for the network drive. I've also set the location to save the PDF to a local directory. No PDF appears.

The log says:|

 [9/18/2024, 8:14:57 AM] Applied filter "Order - Bell Internet Bill" to message from Bell <noreply.business@bell.ca> - Your business e-bill is ready at 9/17/2024, 9:25:32 PM Print

[9/18/2024, 8:14:57 AM] Applied filter "Order - Bell Internet Bill" to message from Bell <noreply.business@bell.ca> - Your business e-bill is ready at 9/17/2024, 9:25:32 PM marked as read 

Please let me know what I can do to have the export to PDF work once again.

Thanks.

Jeffrey

**Comment by cleidigh** [comment]
@JF1313 
Good to see you again.
I'm not sure I am clear on your exact work flow here.
You indicate that exporting with ietng menus works, correct?
I don't understand how you are using filters to export to PDF? It almost sounds like the PrintingTools NG with FiltaQuila function.
@cleidigh

**Comment by JF1313** [comment]
@cleidigh yes, nice to hear from you as well :-)

The email is not converting to a PDF when being applied through Message Filters. This is the same setup through FiltaQuilla that has worked for quite some time.

When I manually select the email and convert to PDF it works.

Any ideas?

**Comment by cleidigh** [comment]
@JF1313 
Ok so to be clear we are really talking about PrintingTools not ietng, yes?
@cleidigh

**Comment by JF1313** [comment]
@cleidigh
Issue resolved, actually embarrassing as the network path changed. All works now :-)

**Comment by cleidigh** [comment]
ok great 
I like simple resolutions!

**Comment by cleidigh** [comment]
we can close?

**Comment by JF1313** [comment]
@cleidigh Yes, please close.

**Comment by cleidigh** [comment]
cheers @JF1313
