### ISSUE TITLE
Mbox-File cannot be imported

### ISSUE THREAD

**Issue by rcohl10** [thunderbird/import-export-tools-ng#642]
Under Thunderbird version 128.3.1esr (32-Bit) the menu does not provide for import of an mbox file. This problem also occurs with version 14.1.0. Any leads how to access backed up mbox files?

**Comment by cleidigh** [comment]
@rcohl10 
Importing mbox files must be done to a folder in your Local Folders account.
Right click on a folder there and you will see the mbox import options.
@cleidigh

**Comment by mivk** [comment]
I have the same problem: no menu to import .mbox file.

This is in Linux Ubuntu 20.04 with
Thunderbird v, 115.16.0esr (115.16.0+build2-0ubuntu0.20.04.1)
ImportExportTools NG v14.1.2

I right-click on a new empty folder in "Local Folders", and select "ImportExportTools NG >".
The submenu I get is:

    Folder Export (mbox)          >
    Export All Messages In Folder >
    Search And Export Messages
    
    Import Maildir Folder
    Import EML Messages           >
    
    Copy Folder Path
    Open Folder Directory
    
    Options
    Help

My Thunderbird is configured to use Maildir format.

    user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/maildirstore;1");
    ...
    user_pref("mail.serverDefaultStoreContractID", "@mozilla.org/msgstore/maildirstore;1");

Maybe .mbox import doesn't work when TB uses Maildir?

**Comment by cleidigh** [comment]
@mivk 
You are correct. It is not possible to import an mbox to a maildir store.
One workaround would be to temporarily setup another Local Folder, but define it's store type as mbox. You can use my Local Folders addon to do this.
https://addons.thunderbird.net/en-US/thunderbird/addon/localfolder/?src=ss

Once you have the mbox local folder setup you import the mbox there then you can copy folders. If not needed after, you can remove the Local Folder.
@cleidigh

**Comment by mivk** [comment]
Yes, after using your extension to add a new Local folder and setting it to "Message Store Type: ... mbox", it worked fine . Thank you!
(For others with the same problem: After installing the extension, no restart of TB needed. Go to "Account Settings", click "Account Actions" and select "Add Local Folder...")

**Comment by cleidigh** [comment]
@mivk 
Great, glad that worked for you.
@cleidigh
