### ISSUE TITLE
Export to CSV is missing body

### ISSUE THREAD

**Issue by BerylTP** [thunderbird/import-export-tools-ng#644]
Hello

When I export to CSV, the file only contains 7 columns. There are no column headers.

The contents of these columns are the Subject, Sender, Recipient, Date, asterisk (attachment indicator?), a number of varying length average about 6 characters and finally a column with "Subject:"

It doesn't have body or the attachment names.

UPDATE - Solved

I had opened the CSV with Excel 2021; however I just tried opening it with LibreOffice Calc and the body were there. (Attachment names are in the body)

**Comment by cleidigh** [comment]
@BerylTP 
Will close
