### ISSUE TITLE
Import-Export-Tools-NG not working on reinstall

### ISSUE THREAD

**Issue by mericanpi** [thunderbird/import-export-tools-ng#645]
I had to reinstall Ubuntu recently, gladly I had been using this product to create backups and was able to reinstall easily from backup.
Since reinstalling, I can no longer run backups. I ran the log and found a "file access denied' error. I have checked ownership of the folders and it all seemed fine. 
Logs are pasted below, do you have any suggestions? Thunderbird can download attachments to that folder OK. Is this even the likely cause of the problem? I run the backup and the progress bar never moves. 

Uncaught NS_ERROR_FILE_ACCESS_DENIED: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.createUnique]
    start chrome://mboximport/content/mboximport/autobackup.js:153
    OpenBackupDialog chrome://mboximport/content/mboximport/messengerOL.js:95
    expMenuDispatcher chrome://mboximport/content/mboximport/expMenuDispatcher.js:169
    observe jar:file:///home/lvm/snap/thunderbird/common/.thunderbird/1yts595n.IETimport/extensions/ImportExportToolsNG@cleidigh.kokkini.net.xpi!/chrome/content/mboximport/modules/notifyTools.js:60
    notifyExperiment jar:file:///home/lvm/snap/thunderbird/common/.thunderbird/1yts595n.IETimport/extensions/ImportExportToolsNG@cleidigh.kokkini.net.xpi!/api/NotifyTools/implementation.js:44
    notifyExperiment jar:file:///home/lvm/snap/thunderbird/common/.thunderbird/1yts595n.IETimport/extensions/ImportExportToolsNG@cleidigh.kokkini.net.xpi!/api/NotifyTools/implementation.js:43
    result resource://gre/modules/ExtensionParent.sys.mjs:1221
    withCallContextData resource://gre/modules/ExtensionParent.sys.mjs:664
    result resource://gre/modules/ExtensionParent.sys.mjs:1220
    withPendingBrowser resource://gre/modules/ExtensionParent.sys.mjs:674
    result resource://gre/modules/ExtensionParent.sys.mjs:1219
    callAndLog resource://gre/modules/ExtensionParent.sys.mjs:1170
    recvAPICall resource://gre/modules/ExtensionParent.sys.mjs:1218
[autobackup.js:153](chrome://mboximport/content/mboximport/autobackup.js)
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. 2 [msgHdrView.js:4214:7](chrome://messenger/content/msgHdrView.js)
IETNG: Start backup check
end script load 
Date Thu Oct 24 2024 23:16:59 GMT+1100 (Australian Eastern Daylight Time)

**Comment by cleidigh** [comment]
@mericanpi 
Was this a flatpak install? I have heard issues with those.
Did you try different directories?
@cleidigh

**Comment by mericanpi** [comment]
Flatpak install - not heard of that term. 
I did install the plugin through the plugin service on Thunderbird, and used a backup from my old install. I can see why that would be called a flatpak - if so then yes.
I have tried downloading to a few directories, and I have downloaded attachments through Thunderbird to the same directories to test permissions. 

Do you have any suggestions on other ways to install? I was not aware of a command line install procedure.

**Comment by mericanpi** [comment]
Actually - it just started working..... Sorry to waste your time, not sure what I did to fix it but it is working now.

**Comment by cleidigh** [comment]
@mericanpi 
Great, I like problems that go away!
@cleidigh

**Comment by techgeek-khushi-2029** [comment]
You can try these fixes first:

* Restart Thunderbird completely
* Reinstall ImportExportTools NG
* Check Thunderbird compatibility version
* Disable conflicting add-ons temporarily
* Start Thunderbird in Troubleshoot Mode
* Remove old add-on cache files
* Create a fresh Thunderbird profile

Some users also try manual drag-and-drop exports.
The “Save As” option can help for small batches.

Usually, this issue appears after Thunderbird updates.
Add-on permissions or profile corruption can also cause it.

If [ImportExportTools not working](https://www.bitrecover.com/blog/importexporttools-ng-not-working/), try **BitRecover Thunderbird Converter** instead.
It supports bulk exports, multiple profiles, large mailboxes, and filter options.
The tool works offline and keeps folder structure properly intact.
